project:
  type: website

website:
  title: "theflow"
  navbar:
    left:
      - text: "Tutorials"
        file: tutorials/tutorial01.qmd
  sidebar:
    - title: "Tutorials"
      style: "floating"
      border: true
      tools:
        - icon: github
          href: https://github.com/trducng/theflow
      contents:
        - section: "Writing your first flow"
          contents:
            - tutorials/tutorial01.qmd
            - tutorials/tutorial02.qmd
            - tutorials/tutorial03.qmd
  page-navigation: true
  page-footer:
    center: "Copyright 2023, trducng"
    right:
      - icon: github
        href: https://github.com/trducng

format:
  html:
    theme:
      light: cosmo
      dark: solar
    toc: true
